### ISSUE TITLE
Support line thickness setting in front-end

### ISSUE THREAD

**Issue by markpash** [AnyTimeTraveler/pipes-and-rust#3]
It would be nice to be able to change the thickness of the stroke in the frontend, perhaps with some sort of dropdown.

The issue is however that just tweaking the thickness in the JS results in ugly strokes, so setting this might get a little tricky.

Also when tweaking the setting directly in the JS, the browser will consume much more CPU while drawing and eventually lag. This may be a result of either slow JS or the algorithm being too complex. Either way, it might be interesting to try and port the intensive parts of the JS to Rust/WASM and see if it improves anything (with the advantage of some front-to-back code sharing).

I'd be happy to help with any of this. :)

**Comment by AnyTimeTraveler** [comment]
That sounds very cool!
I'm gonna play around with line thickness in vanilla JS first, but I like the idea of doing this in Rust/WASM

**Comment by AnyTimeTraveler** [comment]
I just pushed some changes to master.
They include a basic line thickness dial with the option to let pen pressure influence it or not.
The algorithm may need some work, but I am happy with it so far...

**Comment by markpash** [comment]
> I just pushed some changes to master.
> They include a basic line thickness dial with the option to let pen pressure influence it or not.
> The algorithm may need some work, but I am happy with it so far...

Great, I'll try to give it a go soon, thanks for working on this! :)
Feel free to close this issue if you're happy with your implementation.

**Comment by markpash** [comment]
Sorry, I forgot to check on this. I tried it out and it works great. Thanks! :) I'll close as this is addressed now.
