### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Jakob-SD** [AnyTimeTraveler/pipes-and-rust#6]
Hi there

How do I install this service on my ReMarkable?

**Comment by AnyTimeTraveler** [comment]
The title says uninstall, but your question says install.
I am assuming that you mean to ask, how to remove the software.

1. ssh into the reMarkable
2. Execute the command `systemctl stop pipes-and-rust.service` to stop the program
3. Execute the command `systemctl disable pipes-and-rust.service` to remove the autostart
4. Execute the command `rm /lib/systemd/system/pipes-and-rust.service` to delete the autostart service
5. Execute the command `rm /opt/pipes-and-rust` to delete the program itself

After those steps, you should have removed the software completely.
If you encounter any problems, feel free to comment here.

**Comment by Jakob-SD** [comment]
Hi, thank you very much. I apologize for the typo in the question. Your assumption was correct 🙏
