### ISSUE TITLE
Missing "uninstall" in the released package

### ISSUE THREAD

**Issue by scapella** [AnyTimeTraveler/pipes-and-rust#7]
Hi there,

This is a really minor inconvenience but the uninstall script is not included as part of the released package.

Cheers,

S

**Comment by AnyTimeTraveler** [comment]
Fixed in release 1.0.2
You can also find it to download seperately here:
https://raw.githubusercontent.com/AnyTimeTraveler/pipes-and-rust/master/release/uninstall.sh
