### ISSUE TITLE
Resolution too low to screen share on zoom

### ISSUE THREAD

**Issue by jaanaltosaar** [AnyTimeTraveler/pipes-and-rust#8]
Is there a way to increase the resolution? 

It is pixelated right now (https://github.com/bordaigorl/rmview was not, but is a pain to use -- thanks so much for making this so much easier!!!)

![image](https://user-images.githubusercontent.com/5317244/124613574-60034680-de41-11eb-99ac-848fd3d1e3c3.png)

**Comment by AnyTimeTraveler** [comment]
That should be fixable...
I essentially can just make the window any size and scale the screen of the tablet onto it.
Then you can decide how big the window should be.

I have one more exam in my current exam phase, but afterwards I'd be glad to implement this.
It just be some JavaScript...

Thank you for using my software :)

**Comment by AnyTimeTraveler** [comment]
I just made a small release.
The canvas should now resize with your browser window and not waste any leftover space.
I am not sure if this is really a good solution, as I haven't tested it much, yet.
So I would be glad about your feedback if this helps you.

Here is the link to the new release: https://github.com/AnyTimeTraveler/pipes-and-rust/releases/tag/1.1.0
Running the install script will take care of everything.
If you like the old version better, you can just run the install script of that version again to return to that version.

**Comment by jaanaltosaar** [comment]
Thanks so much! 

This is definitely better, but unfortunately the lines are not crisp. I wonder what the solution may be - vectorizing or svg? No idea how the backend works.

Example:

![image](https://user-images.githubusercontent.com/5317244/125354408-c3094780-e331-11eb-814b-fc9ce3562bbd.png)

(compared to the previous screenshot it is definitely more usable :)

This is definitely far and away the best solution so far in terms of installation ease.

**Comment by AnyTimeTraveler** [comment]
The backend just decodes what the pen does.
It then sends the coordinates and pressure to the frontend via websockets.
Theoretically, you can change the drawing logic completely.
I just don't know enough JavaScript to really do much with it.
If you do, feel free to take a stab at it :)
