### ISSUE TITLE
Hardcoded port 80 conflicts with file transfer http server

### ISSUE THREAD

**Issue by okennedy** [AnyTimeTraveler/pipes-and-rust#9]
Xochitl has a built-in HTTP server that is necessary for transferring files onto the device without having a cloud account.  The default port-80 server of pipes-and-rust conflicts.  It would be helpful to have a way to override the default, e.g., with a command line argument or config file.

**Comment by AnyTimeTraveler** [comment]
Oh, I didn't notice that in my testing.
Probably because I have a cloud account.
I'll think about which way to implement the port override and implement it in the coming weeks.
I'd do it sooner, but am currently short on time.

**Comment by okennedy** [comment]
Thanks for a great tool, btw! 

I'm likewise short on time (and haven't had much of a chance to play with rust), but if I get a few moments I'll do the same.

A command-line argument and/or environment variable should be sufficient.  Both can be easily overridden in the systemd config file.

**Comment by AnyTimeTraveler** [comment]
Good point!
When testing, I usually don't use systemd to start pipes-and-rust, so I forgot that the file basically serves as a config file.
I'll add the environment variable soon.
I think that should not take too much time.
